### ISSUE TITLE
Registration on laptop

### ISSUE THREAD

**Issue by erickson0626** [Stock-Knowledge-Engineering/SK-LMS-App#12]
**Describe the bug**
The registration is up to password only

**Expected behavior**
Show all the fields in the registration form

**Screenshots**
![image](https://user-images.githubusercontent.com/72841240/103996456-d4cc2f80-51d4-11eb-874b-a77e74369086.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jcwebhole** [comment]
thanks... this will be fixed soon
for now you can scroll using your mouse scroll wheel while hovering in that area - this happens in lower resolution screens..
