### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by erickson0626** [Stock-Knowledge-Engineering/SK-LMS-App#16]
When I pressed "tab" continuously, this happened.

![image](https://user-images.githubusercontent.com/72841240/104288976-7f08c780-54f3-11eb-938c-70aaa41eabc3.png)

**Comment by erickson0626** [comment]
sir? only the scroll bar added. but this issue is not yet resolved. thanks
(that's what going to happen if you keep pressing "tab" once you focused your cursor to a certain field)

**Comment by jcwebhole** [comment]
clear you cache.. it should be fine now
